version: '3'
services:
    backend:
        image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
        env_file:
            - .env
        environment:
            - SERVER_NAME=${DOMAIN?Variable not set}
            - SERVER_HOST=https://${DOMAIN?Variable not set}
            # Allow explicit env var override for tests
        build:
          context: ./backend
          dockerfile: backend.dockerfile
        ports:
            - "8081:8000"
        volumes:
            - "./backend:/workspace:rw"
    
    frontend:
        image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
        env_file:
            - .env
        build:
          context: ./frontend
          dockerfile: frontend.dockerfile
        ports:
            - "8585:8501"
        volumes:
            - "./frontend:/app:rw"

    https-portal:
        image: steveltn/https-portal:1
        ports:
            - '80:80'
            - '443:443'
        links:
            - backend
            - frontend
        restart: always
        environment:
            DOMAINS: 'scene-recognition.backend.recipi.io => http://scene-recognition.backend.recipi.io:8081/docs, scene-recognition.recipi.io => http://scene-recognition.recipi.io:8585'
            # STAGE: 'production' # Don't use production until staging works
            # FORCE_RENEW: 'true'
        volumes: 
            - https-portal-data:/var/lib/https-portal
    
volumes:
    https-portal-data: